#!/bin/bash

# We first run "extract_markers.py":
extract_markers.py -c <SGB_ID> -d <database>

#to generate the trees we run the Strainphlan main script:
strainphlan -s <all samples in the tree> -d <database> -m <markers_extracted> -c <SGB_ID> -r <reference_genomes>

#For the trees annotation we use:
#1) a metadata file including cMD+cFMD+Reference Genomes+HeppnerN data used to make the ring annotations ("total_metadata_merged_ALL.csv")
#2) the script used to make the ring annotations that uses that metadata file ("make_annotation_file_ALL.py")

#The annotation output txt files are then used as input for graphlan:
#First, graphlan_annotate.py takes in input the tree generated by strainphlan and the annotation txt file
#Then, graphlan.py takes in input the annotated tree file and generates the output image.